# Generated by Django 4.2.7 on 2025-11-17 04:00

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgcrypto.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.CharField(max_length=255)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted (Soft)"),
                            ("TRANSFER_EXECUTED", "Transfer Executed"),
                            ("CERTIFICATE_ISSUED", "Certificate Issued"),
                            ("CERTIFICATE_CANCELLED", "Certificate Cancelled"),
                            ("TAVS_SUBMITTED", "TAVS Report Submitted"),
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("EXPORT", "Data Exported"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("object_id", models.CharField(max_length=36)),
                ("object_repr", models.CharField(max_length=255)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                (
                    "changed_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_number", models.CharField(max_length=20)),
                (
                    "shares",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OUTSTANDING", "Outstanding (Active)"),
                            ("CANCELLED", "Cancelled (Surrendered for transfer)"),
                            ("REPLACED", "Replaced (Lost/Damaged)"),
                            ("LOST", "Lost/Stolen"),
                            ("ESCROW", "Held in Escrow"),
                        ],
                        default="OUTSTANDING",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("cancellation_date", models.DateField(blank=True, null=True)),
                ("has_legend", models.BooleanField(default=False)),
                ("legend_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("acquisition_date", models.DateField()),
                (
                    "acquisition_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "holding_type",
                    models.CharField(
                        choices=[
                            ("DRS", "Direct Registration System (Book-Entry)"),
                            ("CERTIFICATE", "Physical Certificate"),
                        ],
                        default="DRS",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("is_restricted", models.BooleanField(default=False)),
                ("restriction_type", models.CharField(blank=True, max_length=50)),
                ("restriction_removal_date", models.DateField(blank=True, null=True)),
                (
                    "blockchain_token_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Holding (Shareholder Position)",
                "verbose_name_plural": "Holdings (Shareholder Positions)",
                "ordering": ["issuer", "shareholder", "-share_quantity"],
            },
        ),
        migrations.CreateModel(
            name="Issuer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Full legal company name", max_length=255, unique=True
                    ),
                ),
                (
                    "ticker_symbol",
                    models.CharField(
                        blank=True,
                        help_text="OTC Markets ticker symbol",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "cusip",
                    models.CharField(
                        blank=True,
                        help_text="9-character CUSIP identifier",
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "cik",
                    models.CharField(
                        blank=True,
                        help_text="SEC Central Index Key",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("incorporation_state", models.CharField(max_length=2)),
                ("incorporation_country", models.CharField(default="US", max_length=2)),
                ("incorporation_date", models.DateField(blank=True, null=True)),
                (
                    "total_authorized_shares",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "par_value",
                    models.DecimalField(
                        decimal_places=4, default=0.0001, max_digits=10
                    ),
                ),
                ("agreement_start_date", models.DateField()),
                ("agreement_end_date", models.DateField(blank=True, null=True)),
                ("annual_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tavs_enabled", models.BooleanField(default=False)),
                (
                    "otc_tier",
                    models.CharField(
                        choices=[
                            ("OTCQX", "OTCQX Premier"),
                            ("OTCQB", "OTCQB Venture"),
                            ("OTCID", "OTCID Basic"),
                            ("PINK", "Pink Limited"),
                            ("EXPERT", "Expert Market"),
                            ("NONE", "Not Listed"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("otc_markets_profile_url", models.URLField(blank=True, null=True)),
                ("blockchain_enabled", models.BooleanField(default=False)),
                (
                    "blockchain_network",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "smart_contract_address",
                    models.CharField(blank=True, max_length=42, null=True),
                ),
                ("primary_contact_name", models.CharField(max_length=255)),
                ("primary_contact_email", models.EmailField(max_length=254)),
                ("primary_contact_phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Issuer (Client Company)",
                "verbose_name_plural": "Issuers (Client Companies)",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "security_type",
                    models.CharField(
                        choices=[
                            ("COMMON", "Common Stock"),
                            ("PREFERRED", "Preferred Stock"),
                            ("WARRANT", "Warrant"),
                            ("OPTION", "Stock Option"),
                            ("CONVERTIBLE_NOTE", "Convertible Note"),
                            ("TOKEN", "Security Token"),
                            ("NFT_SECURITY", "NFT-Based Security"),
                        ],
                        max_length=20,
                    ),
                ),
                ("class_designation", models.CharField(max_length=100)),
                (
                    "shares_authorized",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "par_value",
                    models.DecimalField(
                        decimal_places=4, default=0.0001, max_digits=10
                    ),
                ),
                ("voting_rights", models.BooleanField(default=True)),
                (
                    "votes_per_share",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("dividend_rights", models.BooleanField(default=True)),
                (
                    "dividend_preference",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "liquidation_preference",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("conversion_rights", models.BooleanField(default=False)),
                (
                    "conversion_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Unrestricted"),
                            ("RULE_144", "Rule 144 (1-year hold)"),
                            ("RULE_701", "Rule 701 (Employee stock)"),
                            ("REG_S", "Regulation S (Offshore)"),
                            ("REG_D", "Regulation D (Private placement)"),
                            ("CUSTOM", "Custom Restriction"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("restriction_removal_date", models.DateField(blank=True, null=True)),
                ("legend_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Security Class",
                "verbose_name_plural": "Security Classes",
                "ordering": ["issuer", "security_type", "class_designation"],
            },
        ),
        migrations.CreateModel(
            name="Shareholder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            (
                                "JOINT_TENANTS",
                                "Joint Tenants with Rights of Survivorship",
                            ),
                            ("TENANTS_COMMON", "Tenants in Common"),
                            ("ENTITY", "Entity (Corp/LLC/Trust/Partnership)"),
                            ("CUSTODIAN", "Custodian (UTMA/UGMA)"),
                            ("IRA", "Individual Retirement Account"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("entity_name", models.CharField(blank=True, max_length=255)),
                ("entity_type", models.CharField(blank=True, max_length=50)),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tax_id",
                    pgcrypto.fields.TextPGPSymmetricKeyField(blank=True, null=True),
                ),
                (
                    "tax_id_type",
                    models.CharField(
                        choices=[
                            ("SSN", "Social Security Number"),
                            ("EIN", "Employer Identification Number"),
                            ("ITIN", "Individual Taxpayer ID"),
                            ("FOREIGN", "Foreign Tax ID"),
                            ("NONE", "Not Provided"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("accredited_investor", models.BooleanField(default=False)),
                ("accredited_date", models.DateField(blank=True, null=True)),
                ("kyc_verified", models.BooleanField(default=False)),
                ("kyc_verification_date", models.DateField(blank=True, null=True)),
                ("kyc_provider", models.CharField(blank=True, max_length=50)),
                (
                    "wallet_address",
                    models.CharField(blank=True, max_length=42, null=True),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("paper_statements", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Shareholder",
                "verbose_name_plural": "Shareholders",
                "ordering": ["last_name", "first_name", "entity_name"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0.0001)],
                    ),
                ),
                (
                    "transfer_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("transfer_date", models.DateField()),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale (Taxable)"),
                            ("GIFT", "Gift (Non-taxable)"),
                            ("INHERITANCE", "Inheritance"),
                            ("DIVORCE", "Divorce Settlement"),
                            (
                                "CORPORATE_ACTION",
                                "Corporate Action (Dividend, Split, etc.)",
                            ),
                            ("CONVERSION", "Conversion (Preferred → Common)"),
                            ("EXERCISE", "Option/Warrant Exercise"),
                            ("OTHER", "Other"),
                        ],
                        default="SALE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending (Awaiting Documents)"),
                            ("VALIDATING", "Under Review"),
                            ("APPROVED", "Approved (Ready to Execute)"),
                            ("EXECUTED", "Executed (Completed)"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("signature_guaranteed", models.BooleanField(default=False)),
                ("signature_guarantee_date", models.DateField(blank=True, null=True)),
                ("signature_guarantor", models.CharField(blank=True, max_length=255)),
                (
                    "surrendered_certificates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "new_certificates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                (
                    "blockchain_network",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "from_shareholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="core.shareholder",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="core.issuer",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "security_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="core.securityclass",
                    ),
                ),
                (
                    "to_shareholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="core.shareholder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer",
                "verbose_name_plural": "Transfers",
                "ordering": ["-transfer_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shareholder",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="core_shareh_last_na_725e25_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shareholder",
            index=models.Index(
                fields=["entity_name"], name="core_shareh_entity__f8b1e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareholder",
            index=models.Index(fields=["email"], name="core_shareh_email_0780e7_idx"),
        ),
        migrations.AddIndex(
            model_name="shareholder",
            index=models.Index(
                fields=["is_active"], name="core_shareh_is_acti_d61065_idx"
            ),
        ),
        migrations.AddField(
            model_name="securityclass",
            name="converts_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="convertible_from",
                to="core.securityclass",
            ),
        ),
        migrations.AddField(
            model_name="securityclass",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_classes",
                to="core.issuer",
            ),
        ),
        migrations.AddIndex(
            model_name="issuer",
            index=models.Index(
                fields=["ticker_symbol"], name="core_issuer_ticker__a446e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuer",
            index=models.Index(fields=["cusip"], name="core_issuer_cusip_4e56f2_idx"),
        ),
        migrations.AddIndex(
            model_name="issuer",
            index=models.Index(
                fields=["otc_tier"], name="core_issuer_otc_tie_c25170_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuer",
            index=models.Index(
                fields=["is_active"], name="core_issuer_is_acti_ab417a_idx"
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holdings",
                to="core.issuer",
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="security_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holdings",
                to="core.securityclass",
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="shareholder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holdings",
                to="core.shareholder",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificates",
                to="core.issuer",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="replaces_certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by",
                to="core.certificate",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="security_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificates",
                to="core.securityclass",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="shareholder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificates",
                to="core.shareholder",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["issuer", "status"], name="core_transf_issuer__300d59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["from_shareholder"], name="core_transf_from_sh_491a06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["to_shareholder"], name="core_transf_to_shar_013310_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(fields=["status"], name="core_transf_status_d86d0e_idx"),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["transfer_date"], name="core_transf_transfe_fa9c93_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="securityclass",
            unique_together={("issuer", "security_type", "class_designation")},
        ),
        migrations.AddIndex(
            model_name="holding",
            index=models.Index(
                fields=["shareholder", "issuer"], name="core_holdin_shareho_34a1bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holding",
            index=models.Index(
                fields=["issuer", "security_class"],
                name="core_holdin_issuer__e4571a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="holding",
            index=models.Index(
                fields=["is_restricted"], name="core_holdin_is_rest_269917_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["issuer", "certificate_number"],
                name="core_certif_issuer__8c98b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["shareholder", "status"], name="core_certif_shareho_d0de74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["status"], name="core_certif_status_82ddba_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together={("issuer", "certificate_number")},
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="core_auditl_model_n_3fb686_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="core_auditl_timesta_80074f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user"], name="core_auditl_user_id_2ff9b7_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type"], name="core_auditl_action__e03c3d_idx"
            ),
        ),
    ]
