# Generated by Django 4.2.7 on 2025-11-18 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_enable_pgcrypto"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareholder",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shareholder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
