# Generated by Django 4.2.7 on 2025-12-15 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_add_user_to_shareholder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIALING", "Trial Period"),
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELLED", "Cancelled"),
                            ("PAUSED", "Paused"),
                        ],
                        default="TRIALING",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("GROWTH", "Growth"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual price (usually discounted)",
                        max_digits=10,
                    ),
                ),
                (
                    "stripe_price_id_monthly",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_price_id_yearly",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_product_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "max_shareholders",
                    models.IntegerField(
                        default=100, help_text="Maximum shareholders allowed"
                    ),
                ),
                (
                    "max_transfers_per_month",
                    models.IntegerField(
                        default=10, help_text="Maximum transfers per month"
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(default=3, help_text="Maximum admin users"),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of feature flags enabled",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["display_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company/organization name", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Activation"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Customer ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Tenant-specific settings"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PLATFORM_ADMIN", "Platform Administrator"),
                            ("TENANT_ADMIN", "Tenant Administrator"),
                            ("TENANT_STAFF", "Tenant Staff"),
                            ("SHAREHOLDER", "Shareholder"),
                        ],
                        default="SHAREHOLDER",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=False, help_text="Primary contact for the tenant"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Membership",
                "verbose_name_plural": "Tenant Memberships",
                "ordering": ["tenant", "role", "user"],
            },
        ),
        migrations.CreateModel(
            name="TenantInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PLATFORM_ADMIN", "Platform Administrator"),
                            ("TENANT_ADMIN", "Tenant Administrator"),
                            ("TENANT_STAFF", "Tenant Staff"),
                            ("SHAREHOLDER", "Shareholder"),
                        ],
                        default="SHAREHOLDER",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Invitation",
                "verbose_name_plural": "Tenant Invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="core_tenant_slug_bb8545_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["status"], name="core_tenant_status_55a303_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["stripe_customer_id"], name="core_tenant_stripe__ff042b_idx"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="core.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this audit log belongs to (null for system-level logs)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this certificate belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this holding belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="issuer",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this issuer belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issuers",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this shareholder belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shareholders",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this transfer belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="core.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(
                fields=["user", "role"], name="core_tenant_user_id_f63b05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(
                fields=["tenant", "role"], name="core_tenant_tenant__f1e358_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantmembership",
            unique_together={("tenant", "user")},
        ),
        migrations.AddIndex(
            model_name="tenantinvitation",
            index=models.Index(fields=["token"], name="core_tenant_token_c3397a_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantinvitation",
            index=models.Index(
                fields=["email", "status"], name="core_tenant_email_71caff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantinvitation",
            index=models.Index(
                fields=["tenant", "status"], name="core_tenant_tenant__3df442_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="core_subscr_status_deb962_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="core_subscr_stripe__4e5b3f_idx"
            ),
        ),
    ]
