# Generated by Django 4.2.7 on 2025-12-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_multitenancy_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("STARTER", "Starter"),
                    ("PROFESSIONAL", "Professional"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
