# Generated by Django 4.2.7 on 2026-01-01 00:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_alter_subscriptionplan_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareIssuanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("FOUNDER_SHARES", "Founder Shares"),
                            ("SEED_ROUND", "Seed Round Funding"),
                            ("RETAIL", "Retail Investment"),
                            ("FRIENDS_FAMILY", "Friends & Family"),
                        ],
                        help_text="Type of investment - determines if payment is required",
                        max_length=20,
                    ),
                ),
                (
                    "share_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of shares to issue",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_per_share",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price per share",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total payment amount (shares * price)",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("PAYMENT_PROCESSING", "Payment Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING_PAYMENT",
                        help_text="Current status of the issuance request",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Checkout Session ID for payment",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Payment Intent ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("holding_type", models.CharField(default="DRS", max_length=20)),
                ("is_restricted", models.BooleanField(default=False)),
                (
                    "acquisition_type",
                    models.CharField(default="ISSUANCE", max_length=20),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "send_email_notification",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to send email notification after issuance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "holding",
                    models.ForeignKey(
                        blank=True,
                        help_text="The holding created after successful payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issuance_request",
                        to="core.holding",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        help_text="Issuer of the shares",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issuance_requests",
                        to="core.issuer",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who initiated the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_issuance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "security_class",
                    models.ForeignKey(
                        help_text="Security class being issued",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issuance_requests",
                        to="core.securityclass",
                    ),
                ),
                (
                    "shareholder",
                    models.ForeignKey(
                        help_text="Shareholder receiving shares",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issuance_requests",
                        to="core.shareholder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this issuance request belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_issuance_requests",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Issuance Request",
                "verbose_name_plural": "Share Issuance Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="core_sharei_tenant__4abfde_idx",
                    ),
                    models.Index(
                        fields=["shareholder", "status"],
                        name="core_sharei_shareho_b98512_idx",
                    ),
                    models.Index(
                        fields=["stripe_checkout_session_id"],
                        name="core_sharei_stripe__70fbea_idx",
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="core_sharei_status_a4263c_idx",
                    ),
                ],
            },
        ),
    ]
