# Generated by Django 4.2.7 on 2026-01-01 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_share_issuance_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="holding",
            name="held_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When shares were placed in holding bucket",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="released_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When shares were released from holding bucket",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who released the shares",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_holdings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="share_issuance_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the issuance request (for payment tracking)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holdings",
                to="core.shareissuancerequest",
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="status",
            field=models.CharField(
                choices=[
                    ("HELD", "Held (Pending Release)"),
                    ("ACTIVE", "Active (Released)"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                help_text="HELD = in holding bucket, ACTIVE = released to shareholder",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="holding",
            index=models.Index(fields=["status"], name="core_holdin_status_fd0cb9_idx"),
        ),
    ]
