# Generated by Django 4.2.7 on 2026-01-02 18:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_add_holding_bucket_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversion_type",
                    models.CharField(
                        choices=[
                            ("DRS_TO_CERT", "DRS to Physical Certificate"),
                            ("CERT_TO_DRS", "Physical Certificate to DRS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "share_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of shares to convert",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0.0001)],
                    ),
                ),
                (
                    "mailing_address",
                    models.TextField(
                        blank=True,
                        help_text="Mailing address for physical certificate delivery",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (if rejected)"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for admin use"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was processed",
                        null=True,
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True,
                        help_text="Certificate number (if physical certificate issued)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "holding",
                    models.ForeignKey(
                        help_text="Holding being converted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_requests",
                        to="core.holding",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who processed the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_requests_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shareholder",
                    models.ForeignKey(
                        help_text="Shareholder making the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_requests",
                        to="core.shareholder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this request belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_requests",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Request",
                "verbose_name_plural": "Certificate Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="core_certif_tenant__71ef0c_idx",
                    ),
                    models.Index(
                        fields=["shareholder", "status"],
                        name="core_certif_shareho_1775da_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_certif_status_d72046_idx",
                    ),
                ],
            },
        ),
    ]
