# Generated by Django 4.2.7 on 2026-01-02 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_create_certificate_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="admin_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether admin notification email was sent on request submission",
            ),
        ),
        migrations.AddField(
            model_name="certificaterequest",
            name="certificate_pdf_url",
            field=models.CharField(
                blank=True,
                help_text="URL to the generated PDF certificate in S3",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="certificaterequest",
            name="shareholder_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether shareholder notification email was sent",
            ),
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certificate_notification_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Email addresses to notify for certificate requests (JSON array)",
                    ),
                ),
                (
                    "certificate_template_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to custom certificate template",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="Tenant these settings belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_settings",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Settings",
                "verbose_name_plural": "Tenant Settings",
            },
        ),
    ]
