# Generated by Django 4.2.7 on 2026-01-04 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_sprint2_tenant_settings_and_certificate_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermSheetAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "term_sheet_file",
                    models.FileField(
                        help_text="PDF file of the term sheet",
                        upload_to="term_sheets/%Y/%m/",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.IntegerField()),
                (
                    "user_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional context from the founder",
                        null=True,
                    ),
                ),
                (
                    "pre_money_valuation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "post_money_valuation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("new_shares_issued", models.BigIntegerField(blank=True, null=True)),
                (
                    "price_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "option_pool_increase_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "liquidation_preference_multiple",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="e.g., 1.0, 1.5, 2.0",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "liquidation_preference_type",
                    models.CharField(
                        blank=True,
                        help_text="participating, non-participating, or capped",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "anti_dilution_type",
                    models.CharField(
                        blank=True,
                        help_text="full_ratchet, weighted_average, broad_based, or none",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "board_composition",
                    models.JSONField(
                        blank=True,
                        help_text="e.g., {'founder': 2, 'investor': 3, 'independent': 1}",
                        null=True,
                    ),
                ),
                (
                    "founder_shares_before",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("total_shares_before", models.BigIntegerField(blank=True, null=True)),
                (
                    "founder_ownership_before_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("founder_shares_after", models.BigIntegerField(blank=True, null=True)),
                ("total_shares_after", models.BigIntegerField(blank=True, null=True)),
                (
                    "founder_ownership_after_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dilution_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Negative number represents ownership decrease",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ai_full_response",
                    models.JSONField(
                        blank=True,
                        help_text="Complete JSON response from OpenAI",
                        null=True,
                    ),
                ),
                (
                    "plain_english_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Plain English summary of the deal",
                        null=True,
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.0-1.0, confidence in extraction accuracy",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("EXTRACTING", "Extracting Text"),
                            ("ANALYZING", "Analyzing with AI"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_sheet_analyses",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term Sheet Analysis",
                "verbose_name_plural": "Term Sheet Analyses",
                "db_table": "deal_desk_termsheetanalysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scenario_label",
                    models.CharField(
                        help_text="e.g., 'Scenario A', 'Scenario B'", max_length=50
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'Counter with Standard Terms'", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed explanation of proposed changes"
                    ),
                ),
                (
                    "new_valuation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "new_dilution_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "likelihood_of_acceptance",
                    models.CharField(
                        blank=True,
                        help_text="'High', 'Medium', or 'Low'",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="deal_desk.termsheetanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis Scenario",
                "verbose_name_plural": "Analysis Scenarios",
                "db_table": "deal_desk_analysisscenario",
                "ordering": ["scenario_label"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisRedFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        help_text="e.g., 'full_ratchet_anti_dilution', 'participating_preferred'",
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'Full Ratchet Anti-Dilution Detected'",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Plain English explanation of the risk"),
                ),
                (
                    "prevalence",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Only 5% of seed deals include this'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        help_text="Actionable advice on how to address this"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="red_flags",
                        to="deal_desk.termsheetanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis Red Flag",
                "verbose_name_plural": "Analysis Red Flags",
                "db_table": "deal_desk_analysisredflag",
                "ordering": ["-severity", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="termsheetanalysis",
            index=models.Index(
                fields=["tenant", "-created_at"], name="deal_desk_t_tenant__f2ea20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termsheetanalysis",
            index=models.Index(
                fields=["tenant", "status"], name="deal_desk_t_tenant__609156_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termsheetanalysis",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="deal_desk_t_created_8f7827_idx",
            ),
        ),
    ]
